export const catalog = [
  {
    nome: "Casa 2 Quartos — Setor Della Penna",
    quartos: 2,
    bairro: "Setor Della Penna, Goiânia/GO",
    referencia: "A 9 min do Shopping Plaza Doro",
    entrada: 10000,
    renda_minima: 7000,
    descricao: "Casa 2 quartos com quintal privativo. Ótima localização, próxima a comércio e serviços. Condições facilitadas pelo MCMV.",
    diferenciais: ["2 quartos confortáveis", "Quintal privativo", "Ótima localização", "A 9 min do Shopping Plaza Doro"],
    fotos: []
  },
  {
    nome: "Casa 2 Quartos — Setor das Nações",
    quartos: 2,
    bairro: "Setor das Nações, Goiânia/GO",
    referencia: "A 10 min do Shopping Cidade Jardim",
    entrada: 64000,
    renda_minima: null,
    descricao: "Casa usada, pronta para morar. Sala integrada, cozinha americana, banheiro social, garagem e quintal.",
    diferenciais: ["2 quartos", "Sala integrada", "Cozinha americana", "Garagem", "Quintal", "Pronta para morar", "A 10 min do Shopping Cidade Jardim"],
    fotos: []
  },
  {
    nome: "Casa 3 Quartos — Pilar dos Sonhos (Região Noroeste)",
    quartos: 3,
    bairro: "Pilar dos Sonhos, Região Noroeste, Goiânia/GO",
    referencia: "Ao lado do Supermercado Atacadão, 5 min do Portal Shopping",
    entrada: 15000,
    renda_minima: 8000,
    descricao: "Casa 3 quartos com quintal. Excelente localização na Região Noroeste, ao lado do Supermercado Atacadão e a apenas 5 min do Portal Shopping. Condições facilitadas pelo MCMV.",
    diferenciais: ["3 quartos", "Quintal", "Excelente localização", "Ao lado do Atacadão", "5 min do Portal Shopping"],
    fotos: [
      "https://i.ibb.co/m548F58j/IMG-6528.jpg",
      "https://i.ibb.co/jZ6pgDBh/IMG-6530.jpg",
      "https://i.ibb.co/nMg7NKG6/IMG-6533.jpg",
      "https://i.ibb.co/q3wCKQff/IMG-6543.jpg",
      "https://i.ibb.co/xSXLpLWd/IMG-6548.jpg",
      "https://i.ibb.co/FqJt63pW/IMG-6553.jpg",
      "https://i.ibb.co/Qvqcvz8C/IMG-6558.jpg",
      "https://i.ibb.co/mFgjL41C/IMG-6569.jpg",
      "https://i.ibb.co/cSpQLf3P/IMG-6577.jpg",
      "https://i.ibb.co/T9tFwzP/IMG-6582.jpg",
      "https://i.ibb.co/QvFysr5q/IMG-6598.jpg",
      "https://i.ibb.co/RGfdp2NJ/IMG-6603.jpg",
      "https://i.ibb.co/bjbxPxBT/IMG-6608.jpg",
      "https://i.ibb.co/yByyYYsW/IMG-6612.jpg",
      "https://i.ibb.co/7d21x57b/IMG-6613.jpg",
      "https://i.ibb.co/tw3Y7HM1/IMG-6618.jpg"
    ]
  },
  {
    nome: "Casa 2 Quartos — Setor Carolina Parque",
    quartos: 2,
    bairro: "Setor Carolina Parque, Goiânia/GO",
    referencia: "Ao lado do João Braz, 10 min do Shopping Cidade Jardim",
    entrada: 15000,
    renda_minima: 7000,
    descricao: "Casa 2 quartos com excelente localização no Setor Carolina Parque. Próxima a comércios e serviços.",
    diferenciais: ["2 quartos", "Excelente localização", "Próxima ao João Braz", "10 min do Shopping Cidade Jardim"],
    fotos: []
  },
  {
    nome: "Casa 2 Quartos — Setor Monte Pascoal",
    quartos: 2,
    bairro: "Setor Monte Pascoal, Goiânia/GO",
    referencia: "A 10 min do Shopping América",
    entrada: 50000,
    renda_minima: null,
    descricao: "Casa nova com mega quintal. Ótima para morar ou investir. Ideal para área gourmet ou espaço para a família.",
    diferenciais: ["2 quartos", "Mega quintal", "Casa nova", "A 10 min do Shopping América"],
    fotos: []
  },
  {
    nome: "Casa 2 Quartos — Setor Santa Fé",
    quartos: 2,
    bairro: "Setor Santa Fé, Goiânia/GO",
    referencia: "Próxima ao Moinho dos Ventos",
    entrada: 35000,
    renda_minima: 8000,
    descricao: "Casa 2 quartos com garagem coberta e quintal nos fundos. Fácil acesso pela região do Santa Fé.",
    diferenciais: ["2 quartos", "Garagem coberta", "Quintal nos fundos", "Próxima ao Moinho dos Ventos"],
    fotos: []
  },
  {
    nome: "Casa 2 Quartos — Botânico",
    quartos: 2,
    bairro: "Setor Botânico, Goiânia/GO",
    referencia: "A 9 min do Shopping Plaza D'Oro",
    entrada: 9000,
    renda_minima: 7000,
    descricao: "Casa 2 quartos com mega quintal para aproveitar com a família, receber amigos, montar área gourmet ou deixar as crianças brincarem com liberdade. Excelente localização e condições facilitadas pelo MCMV.",
    diferenciais: ["2 quartos", "Mega quintal", "Área gourmet", "A 9 min do Shopping Plaza D'Oro"],
    fotos: [
      "https://i.ibb.co/QFsJhKpV/IMG-7699.jpg",
      "https://i.ibb.co/vxTQTdvL/IMG-7741.jpg",
      "https://i.ibb.co/chqLXfqD/IMG-7756.jpg",
      "https://i.ibb.co/3yy5d0hD/IMG-7761.jpg",
      "https://i.ibb.co/CKnKV3m3/IMG-7775.jpg",
      "https://i.ibb.co/NgW46TKW/IMG-8343.jpg",
      "https://i.ibb.co/PKzLZnK/IMG-8359.jpg",
      "https://i.ibb.co/nMW03D67/IMG-8365.jpg",
      "https://i.ibb.co/SY5DC6f/IMG-8375.jpg",
      "https://i.ibb.co/LX4jrf0R/IMG-8376.jpg",
      "https://i.ibb.co/ZpxD58mk/IMG-8383.jpg"
    ]
  },
];
